language: php
php:
  - 7.3
  - 7.4

before_install:
  - mysql -e 'CREATE DATABASE autowebinar_testy;'

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan migrate --force

script:
  - composer test

services:
  - mysql

env:
  global:
      - DB_DATABASE=autowebinar_testy DB_USERNAME=travis DB_PASSWORD=